### ISSUE TITLE
cannot compile iou.cpp

### ISSUE THREAD

**Issue by jiangwei221** [CheckBoxStudio/IoU#1]
I tried to compile iou.cpp with: g++ -c iou.cpp
but got following errors:
```
In file included from iou.cpp:13:
./iou.h:141:23: error: anonymous struct member 'p1' has a non-trivial copy constructor
                Point p1;
                      ^
./iou.h:53:9: note: because type 'IOU::Vec2<double>' has a user-provided copy constructor
        Vec2(const Vec2& p) : x(p.x), y(p.y) {}
```

**Comment by weiquanmao** [comment]
Please check the latest submission [4d28a31](https://github.com/CheckBoxStudio/IoU/tree/4d28a31d72b604c269a1109aaed1d694a6d1114e), where the `Union` members, which require `trivial copy constructor` and `trivial copy assignment operator`,  are removed.

**Comment by jiangwei221** [comment]
Thanks for the fixing!
